### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by MrMeesek** [R3nzTheCodeGOD/I-moved-to-my-own-repo#29]
Hello! First of all let me say thank you for your work. the tool is amazing!

I was playing an Aram game a few moments ago and I had a random crash. the tool was up and running, the client too, just the game crashed (I was using warden quinn). The interesting thing is that I was playing online with a friend and he was using the tool as well and we crashed at exactely the same time. Different house, different wifi etc... We were just using the same tool (i built it for him yesterday), and suddenly without anything in particular during the game it crashed for both in the same way.

**Comment by R3nzTheCodeGOD** [comment]
I think the code crashed in the part I referenced, maybe someone enlarged and exploded the poro, which may have caused an undefined behavior, but I'm not sure.

https://github.com/R3nzTheCodeGOD/R3nzSkin/blob/b2729c3ca0237aaaaa1656197520e014c3da9841/R3nzSkin/Hooks.cpp#L335-L350

**Comment by MrMeesek** [comment]
Interesting. I am going to comment it out and test it during this week and let you know. 

The crash happened to me two days ago in a normal game as well, but i was playing alone.
